version: '3.8'

services:
  back-ventas:
    image: ${DOCKERHUB_USERNAME}/back-ventas:latest
    container_name: innovatech-back-ventas
    restart: always
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:mysql://10.0.128.66:3306/db_innovatech?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    volumes:
      - ventas-logs:/app/logs
    networks:
      - innovatech-net

  back-despachos:
    image: ${DOCKERHUB_USERNAME}/back-despachos:latest
    container_name: innovatech-back-despachos
    restart: always
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:mysql://10.0.128.66:3306/db_innovatech?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    volumes:
      - despachos-logs:/app/logs
    networks:
      - innovatech-net

volumes:
  ventas-logs:
  despachos-logs:

networks:
  innovatech-net:
    driver: bridge