spring.application.name=Springboot-API-REST
server.port=8082
spring.web.allow-cors=true

# Configuración de la base de datos PostgreSQL en AWS RDS
spring.datasource.url=jdbc:postgresql://${DB_ENDPOINT}:${DB_PORT}/${DB_NAME}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.platform=postgresql

# Configuración de Hibernate
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.path=/swagger-ui.html