name: CD Despachos Private Deployment

on:
  push:
    branches:
      - deploy
    paths:
      - 'back-Despachos_SpringBoot/**'
      - '.github/workflows/despachos-pipeline.yml'
      - 'docker-compose.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub (Native)
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/back-despachos:latest ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/back-despachos:latest

    - name: Deploy via SSH ProxyJump
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.FRONTEND_PUBLIC_IP }}
        username: ec2-user
        key: ${{ secrets.AWS_SSH_KEY }}
        sync: true
        script: |
          # 1. Crear red de docker si no existe en el Backend (con sudo)
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/Llave-Innovatech.pem ec2-user@10.0.142.7 "sudo docker network create innovatech-net || true"

          # 2. Desplegar de forma directa con Docker Run en el Backend
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/Llave-Innovatech.pem ec2-user@10.0.142.7 << 'EOF'
          # Autenticarse en Docker Hub desde el Backend con sudo
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

          # Detener y borrar contenedor anterior si existe con sudo
          sudo docker stop innovatech-back-despachos || true
          sudo docker rm innovatech-back-despachos || true

          # Descargar última imagen con sudo
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/back-despachos:latest

          # Correr el contenedor con sus variables correspondientes con sudo
          sudo docker run -d \
            --name innovatech-back-despachos \
            --restart always \
            -p 8082:8082 \
            --network innovatech-net \
            -e SERVER_PORT=8082 \
            -e SPRING_DATASOURCE_URL=jdbc:postgresql://10.0.155.105:5432/db_innovatech \
            -e SPRING_DATASOURCE_USERNAME=root \
            -e SPRING_DATASOURCE_PASSWORD=rootpassword \
            -v despachos-logs:/app/logs \
            ${{ secrets.DOCKERHUB_USERNAME }}/back-despachos:latest
          EOF