name: CD Despachos Private Deployment

on:
  push:
    branches:
      - deploy
    paths:
      - 'back-Despachos_SpringBoot/**'
      - '.github/workflows/despachos-pipeline.yml'
      - 'docker-compose.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub (Native)
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/back-despachos:latest ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/back-despachos:latest

    - name: Copy Docker Compose to Frontend via SSH
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.FRONTEND_PUBLIC_IP }}
        username: ec2-user
        key: ${{ secrets.AWS_SSH_KEY }}
        source: "docker-compose.yml"
        target: "/home/ec2-user/"

    - name: Deploy via SSH ProxyJump
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.FRONTEND_PUBLIC_IP }}
        username: ec2-user
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@10.0.128.158 "mkdir -p ~/innovatech"
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa /home/ec2-user/docker-compose.yml ec2-user@10.0.128.158:~/innovatech/docker-compose.yml

          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@10.0.128.158 << 'EOF'
            cd ~/innovatech
            DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}" sudo -E docker compose pull back-despachos
            DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}" sudo -E docker compose up -d back-despachos
          EOF