name: CD Frontend Deployment

on:
  push:
    branches:
      - deploy
    paths:
      - 'front_despacho/**'
      - '.github/workflows/frontend-pipeline.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub (Native)
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/front-despacho:latest ./front_despacho
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/front-despacho:latest

    - name: Deploy via SSH ProxyJump
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.FRONTEND_PUBLIC_IP }}
        username: ec2-user
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/front-despacho:latest
          sudo docker stop front-despacho || true
          sudo docker rm front-despacho || true
          sudo docker run -d --name front-despacho -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/front-despacho:latest