name: CD Frontend Deployment

on:
  push:
    branches:
      - deploy
    paths:
      - 'front_despacho/**'
      - '.github/workflows/frontend-pipeline.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and Push Frontend Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/front-despacho:latest ./front_despacho
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/front-despacho:latest

    - name: Deploy to Frontend Instance (Public)
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.FRONTEND_PUBLIC_IP }}
        username: ec2-user
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          mkdir -p ~/innovatech-front
          cd ~/innovatech-front

          # Crear el docker-compose local para el Frontend
          cat << 'EOF' > docker-compose.yml
          version: '3.8'

          services:
            frontend:
              image: ${{ secrets.DOCKERHUB_USERNAME }}/front-despacho:latest
              container_name: innovatech-front-despacho
              restart: always
              ports:
                - "80:80"
              environment:
                - REACT_APP_API_VENTAS_URL=http://18.214.44.59:8081
                - REACT_APP_API_DESPACHOS_URL=http://18.214.44.59:8082
          EOF

          sudo docker compose pull
          sudo docker compose up -d