name: CD Frontend Deployment

on:
  push:
    branches:
      - deploy
    paths:
      - 'front_despacho/**'
      - '.github/workflows/frontend-pipeline.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and Push Frontend Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/front-despacho:latest ./front_despacho
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/front-despacho:latest

    - name: Deploy to Frontend Instance (Public)
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.FRONTEND_PUBLIC_IP }}
        username: ec2-user
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          # Autenticarse en Docker Hub en la máquina pública
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

          # Detener y limpiar contenedor anterior si existe
          sudo docker stop innovatech-front-despacho || true
          sudo docker rm innovatech-front-despacho || true

          # Forzar descarga de la última versión
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/front-despacho:latest

          # Levantar el contenedor mapeando el puerto 80 nativo
          sudo docker run -d \
            --name innovatech-front-despacho \
            --restart always \
            -p 80:80 \
            -e REACT_APP_API_VENTAS_URL=http://18.214.44.59:8081 \
            -e REACT_APP_API_DESPACHOS_URL=http://18.214.44.59:8082 \
            ${{ secrets.DOCKERHUB_USERNAME }}/front-despacho:latest